### ISSUE TITLE
After upgrading to angular 13 storybook is not working.

### ISSUE THREAD

**Issue by km4dlpx** [Luchanso/storybook-typescript-problem#3]
ModuleParseError: Module parse failed: Unexpected token (46:2)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
|         })
|     ]
> } as Meta;
| 
| const Template: Story<DxBaseDialogComponent> = (args: DxBaseDialogComponent) => ({
    at handleParseError (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:976:19)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:800:11)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js:59:71
ModuleParseError: Module parse failed: Unexpected character '@' (20:0)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
| import { DxDialogService } from '../dx-dialog.service';
| 
> @Component({
|     selector: 'dx-confirm-dialog-demo',
|     template: `
    at handleParseError (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:976:19)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:800:11)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js:59:71
ModuleParseError: Module parse failed: Unexpected character '@' (20:0)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
| import { DxDialogService } from '../dx-dialog.service';
| 
> @Component({
|     selector: 'dx-info-dialog-demo',
|     template: `
    at handleParseError (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:976:19)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:800:11)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/Users/kapilmittal/workspace/dx-gui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/kapilmittal/workspace/dx-gui/node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js:59:71

**Comment by km4dlpx** [comment]
Hey, can you share the similar solution for angular also.
